feat: создан проект ТЗ 9
DariaChagadaeva/java-filmorate pull request #2
Opened 2023-01-15 19:52 UTC by DariaChagadaeva

2023-01-16 08:08 UTC, ErkinKasymaliev requested changes
Привет!
Почему вы сделали storage-ы если вы еще не проходили это и по ТЗ не надо?

2023-01-16 08:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +public interface UserStorage {
почему вы сделали storage-ы если вы еще не прошли это и в ТЗ нет?

2023-01-16 09:41 UTC, DariaChagadaeva commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +public interface UserStorage {
В ТЗ было написано, что можно сделать так же как мы делали с менеджером задач, я сделала по аналогии с TaskManager и InMemoryTaskManager. На Q&A был вопрос про dependency injection и куратор показал на примере нашего ТЗ про storage и я попробовала, возможно я что-то не так поняла? 
Также куратор рассказывая про SprinBootTest кратко объяснял про мок и стаб, и сказал что можно прочитать про mockMvc и попробовать сделать тесты таким образом.

2023-01-17 06:22 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-01-17 06:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    InMemoryFilmStorage storage;
добавьте модификатор доступа private

2023-01-17 06:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(film.getDescription() != null && film.getDescription().length() > MAX_NAME_SIZE) {
у вас же стоит уже @Size в Film, поэтому film.getDescription().length() > MAX_NAME_SIZE не нужно.
Проверьте этот метод, тут некоторые вещи не нужны, так как нужные аннотации в модельке у вас есть

2023-01-17 06:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if(user.getEmail().isEmpty() || user.getEmail() == null || !(user.getEmail().contains("@"))) {
Проверьте этот метод, тут некоторые вещи не нужны, так как нужные аннотации в модельке у вас есть

2023-01-17 06:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    InMemoryUserStorage storage;
добавьте модификатор доступа private

2023-01-17 11:05 UTC, DariaChagadaeva commented
Все правки внесла.

2023-01-17 16:16 UTC, ErkinKasymaliev approved these changes
работа принята

2023-01-19 10:46 UTC, merged